name 'dhoppe-ntp'
version '0.0.2'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-ntp'
source 'git://github.com/dhoppe/puppet-ntp'
summary 'NTP Module'
description 'NTP Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
